

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:3000"
    depends_on:
      - pedidos
      - pagamentos
      - estoque

  pedidos:
    build: ./pedidos

  pagamentos:
    build: ./pagamentos

  estoque:
    build: ./estoque
