apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque
  namespace: pedidos-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estoque
  template:
    metadata:
      labels:
        app: estoque
    spec:
      containers:
        - name: estoque
          image: estoque:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
