apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estoque
  template:
    metadata:
      labels:
        app: estoque
    spec:
      containers:
        - name: estoque
          image: pedidos-veloz/estoque:1.0
          ports:
            - containerPort: 3000
