apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
  namespace: pedidos-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      containers:
        - name: pagamentos
          image:  pagamentos:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
