apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      containers:
        - name: pagamentos
          image:  pedidos-veloz/pagamentos:1.0
          ports:
            - containerPort: 3000
