name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push API Gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/api-gateway:latest ./api-gateway
          docker push ${{ secrets.DOCKER_USER }}/api-gateway:latest

      - name: Build & Push Pedidos
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/pedidos:latest ./pedidos
          docker push ${{ secrets.DOCKER_USER }}/pedidos:latest

      - name: Build & Push Pagamentos
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/pagamentos:latest ./pagamentos
          docker push ${{ secrets.DOCKER_USER }}/pagamentos:latest

      - name: Build & Push Estoque
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/estoque:latest ./estoque
          docker push ${{ secrets.DOCKER_USER }}/estoque:latest
