name: CI Pipeline - Microsserviços

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Executar testes (simulados)
        run: echo "Testes executados com sucesso"

      - name: Usar secret do GitHub
        run: echo "Secret configurado com sucesso"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build do microsserviço PEDIDOS
        run: docker build -t pedidos-veloz/pedidos:ci ./pedidos

      - name: Build do microsserviço PAGAMENTOS
        run: docker build -t pedidos-veloz/pagamentos:ci ./pagamentos

      - name: Build do microsserviço ESTOQUE
        run: docker build -t pedidos-veloz/estoque:ci ./estoque
